// @ts-nocheck
import * as __fd_glob_64 from "../content/docs/general-surgery/hbp/recurrent-pyogenic-cholangitis.mdx?collection=docs"
import * as __fd_glob_63 from "../content/docs/general-surgery/hbp/primary-sclerosing-cholangitis.mdx?collection=docs"
import * as __fd_glob_62 from "../content/docs/general-surgery/hbp/primary-biliary-cirrhosis.mdx?collection=docs"
import * as __fd_glob_61 from "../content/docs/general-surgery/hbp/pancreatic-cancer.mdx?collection=docs"
import * as __fd_glob_60 from "../content/docs/general-surgery/hbp/mirizzi-syndrome.mdx?collection=docs"
import * as __fd_glob_59 from "../content/docs/general-surgery/hbp/malignant-biliary-obstruction-mbo.mdx?collection=docs"
import * as __fd_glob_58 from "../content/docs/general-surgery/hbp/liver-cirrhosis.mdx?collection=docs"
import * as __fd_glob_57 from "../content/docs/general-surgery/hbp/liver-abscess.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/general-surgery/hbp/jaundice.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/general-surgery/hbp/hepatocellular-carcinoma-hcc.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/general-surgery/hbp/gallstones.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/general-surgery/hbp/gallbladder-cancer.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/general-surgery/hbp/cholangiocarcinoma.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/general-surgery/hbp/biliary-cysts.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/general-surgery/hbp/acute-pancreatitis.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/general-surgery/hbp/acute-cholecystitis.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/general-surgery/hbp/acute-cholangitis.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/general-surgery/lower-gi/volvulus.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/general-surgery/lower-gi/rectal-prolapse.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/general-surgery/lower-gi/intestinal-obstruction.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/general-surgery/lower-gi/intestinal-ischemia.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/general-surgery/lower-gi/inflammatory-bowel-disease-ulcerative-colitis.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/general-surgery/lower-gi/inflammatory-bowel-disease-crohn-s-disease.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/general-surgery/lower-gi/hemorrhoids.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/general-surgery/lower-gi/diverticular-disease.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/general-surgery/lower-gi/anorectal-fistula.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/general-surgery/lower-gi/anorectal-abscess.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/general-surgery/lower-gi/anal-fissure.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/general-surgery/lower-gi/acute-appendicitis.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/psychiatry/stress-related-disorders.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/psychiatry/somatoform-disorders.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/psychiatry/sleep-disorders.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/psychiatry/schizophrenia-and-related-disorders.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/psychiatry/psychosexual-disorders.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/psychiatry/personality-and-personality-disorders.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/psychiatry/other-psychiatric-conditions-in-child-psychiatry.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/psychiatry/oppositional-defiant-and-conduct-disorders.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/psychiatry/obsessive-compulsive-disorder.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/psychiatry/misuse-of-substance.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/psychiatry/misuse-of-alcohol-and-alcohol-related-disorders.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/psychiatry/major-depressive-disorder.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/psychiatry/eating-disorders.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/psychiatry/depressive-disorders.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/psychiatry/dementia.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/psychiatry/delirium.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/psychiatry/cluster-c-anxious-personality-disorders.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/psychiatry/cluster-b-dramatic-personality-disorders.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/psychiatry/cluster-a-odd-personality-disorders.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/psychiatry/bipolar-disorder.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/psychiatry/autistic-spectrum-disorder-asd.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/psychiatry/attention-deficit-hyperactivity-disorder-adhd.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/psychiatry/assessment-in-child-psychiatry.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/psychiatry/approach-to-psychotic-symptoms.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/psychiatry/approach-to-mood-disturbances.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/psychiatry/anxiety-disorders.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/general-surgery/peritonitis.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/general-surgery/index.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/general-surgery/hernia.mdx?collection=docs"
import * as __fd_glob_6 from "../content/docs/medicine/placeholder.mdx?collection=docs"
import * as __fd_glob_5 from "../content/docs/medicine/index.mdx?collection=docs"
import * as __fd_glob_4 from "../content/docs/index.mdx?collection=docs"
import { default as __fd_glob_3 } from "../content/docs/general-surgery/lower-gi/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/general-surgery/hbp/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/medicine/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/general-surgery/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"general-surgery/meta.json": __fd_glob_0, "medicine/meta.json": __fd_glob_1, "general-surgery/hbp/meta.json": __fd_glob_2, "general-surgery/lower-gi/meta.json": __fd_glob_3, }, {"index.mdx": __fd_glob_4, "medicine/index.mdx": __fd_glob_5, "medicine/placeholder.mdx": __fd_glob_6, "general-surgery/hernia.mdx": __fd_glob_7, "general-surgery/index.mdx": __fd_glob_8, "general-surgery/peritonitis.mdx": __fd_glob_9, "psychiatry/anxiety-disorders.mdx": __fd_glob_10, "psychiatry/approach-to-mood-disturbances.mdx": __fd_glob_11, "psychiatry/approach-to-psychotic-symptoms.mdx": __fd_glob_12, "psychiatry/assessment-in-child-psychiatry.mdx": __fd_glob_13, "psychiatry/attention-deficit-hyperactivity-disorder-adhd.mdx": __fd_glob_14, "psychiatry/autistic-spectrum-disorder-asd.mdx": __fd_glob_15, "psychiatry/bipolar-disorder.mdx": __fd_glob_16, "psychiatry/cluster-a-odd-personality-disorders.mdx": __fd_glob_17, "psychiatry/cluster-b-dramatic-personality-disorders.mdx": __fd_glob_18, "psychiatry/cluster-c-anxious-personality-disorders.mdx": __fd_glob_19, "psychiatry/delirium.mdx": __fd_glob_20, "psychiatry/dementia.mdx": __fd_glob_21, "psychiatry/depressive-disorders.mdx": __fd_glob_22, "psychiatry/eating-disorders.mdx": __fd_glob_23, "psychiatry/major-depressive-disorder.mdx": __fd_glob_24, "psychiatry/misuse-of-alcohol-and-alcohol-related-disorders.mdx": __fd_glob_25, "psychiatry/misuse-of-substance.mdx": __fd_glob_26, "psychiatry/obsessive-compulsive-disorder.mdx": __fd_glob_27, "psychiatry/oppositional-defiant-and-conduct-disorders.mdx": __fd_glob_28, "psychiatry/other-psychiatric-conditions-in-child-psychiatry.mdx": __fd_glob_29, "psychiatry/personality-and-personality-disorders.mdx": __fd_glob_30, "psychiatry/psychosexual-disorders.mdx": __fd_glob_31, "psychiatry/schizophrenia-and-related-disorders.mdx": __fd_glob_32, "psychiatry/sleep-disorders.mdx": __fd_glob_33, "psychiatry/somatoform-disorders.mdx": __fd_glob_34, "psychiatry/stress-related-disorders.mdx": __fd_glob_35, "general-surgery/lower-gi/acute-appendicitis.mdx": __fd_glob_36, "general-surgery/lower-gi/anal-fissure.mdx": __fd_glob_37, "general-surgery/lower-gi/anorectal-abscess.mdx": __fd_glob_38, "general-surgery/lower-gi/anorectal-fistula.mdx": __fd_glob_39, "general-surgery/lower-gi/diverticular-disease.mdx": __fd_glob_40, "general-surgery/lower-gi/hemorrhoids.mdx": __fd_glob_41, "general-surgery/lower-gi/inflammatory-bowel-disease-crohn-s-disease.mdx": __fd_glob_42, "general-surgery/lower-gi/inflammatory-bowel-disease-ulcerative-colitis.mdx": __fd_glob_43, "general-surgery/lower-gi/intestinal-ischemia.mdx": __fd_glob_44, "general-surgery/lower-gi/intestinal-obstruction.mdx": __fd_glob_45, "general-surgery/lower-gi/rectal-prolapse.mdx": __fd_glob_46, "general-surgery/lower-gi/volvulus.mdx": __fd_glob_47, "general-surgery/hbp/acute-cholangitis.mdx": __fd_glob_48, "general-surgery/hbp/acute-cholecystitis.mdx": __fd_glob_49, "general-surgery/hbp/acute-pancreatitis.mdx": __fd_glob_50, "general-surgery/hbp/biliary-cysts.mdx": __fd_glob_51, "general-surgery/hbp/cholangiocarcinoma.mdx": __fd_glob_52, "general-surgery/hbp/gallbladder-cancer.mdx": __fd_glob_53, "general-surgery/hbp/gallstones.mdx": __fd_glob_54, "general-surgery/hbp/hepatocellular-carcinoma-hcc.mdx": __fd_glob_55, "general-surgery/hbp/jaundice.mdx": __fd_glob_56, "general-surgery/hbp/liver-abscess.mdx": __fd_glob_57, "general-surgery/hbp/liver-cirrhosis.mdx": __fd_glob_58, "general-surgery/hbp/malignant-biliary-obstruction-mbo.mdx": __fd_glob_59, "general-surgery/hbp/mirizzi-syndrome.mdx": __fd_glob_60, "general-surgery/hbp/pancreatic-cancer.mdx": __fd_glob_61, "general-surgery/hbp/primary-biliary-cirrhosis.mdx": __fd_glob_62, "general-surgery/hbp/primary-sclerosing-cholangitis.mdx": __fd_glob_63, "general-surgery/hbp/recurrent-pyogenic-cholangitis.mdx": __fd_glob_64, });