// @ts-nocheck
import * as __fd_glob_74 from "../content/docs/psychiatry/substance-abuse-f1/misuse-of-substance.mdx?collection=docs"
import * as __fd_glob_73 from "../content/docs/psychiatry/substance-abuse-f1/misuse-of-alcohol-and-alcohol-related-disorders.mdx?collection=docs"
import * as __fd_glob_72 from "../content/docs/psychiatry/psychotic-disorders-f2/schizophrenia-and-related-disorders.mdx?collection=docs"
import * as __fd_glob_71 from "../content/docs/psychiatry/psychotic-disorders-f2/approach-to-psychotic-symptoms.mdx?collection=docs"
import * as __fd_glob_70 from "../content/docs/psychiatry/personality-disorders-f6/personality-and-personality-disorders.mdx?collection=docs"
import * as __fd_glob_69 from "../content/docs/psychiatry/personality-disorders-f6/cluster-c-anxious-personality-disorders.mdx?collection=docs"
import * as __fd_glob_68 from "../content/docs/psychiatry/personality-disorders-f6/cluster-b-dramatic-personality-disorders.mdx?collection=docs"
import * as __fd_glob_67 from "../content/docs/psychiatry/personality-disorders-f6/cluster-a-odd-personality-disorders.mdx?collection=docs"
import * as __fd_glob_66 from "../content/docs/psychiatry/organic-mental-disorders-f0/dementia.mdx?collection=docs"
import * as __fd_glob_65 from "../content/docs/psychiatry/organic-mental-disorders-f0/delirium.mdx?collection=docs"
import * as __fd_glob_64 from "../content/docs/psychiatry/neurotic-stress-somatoform-f4/stress-related-disorders.mdx?collection=docs"
import * as __fd_glob_63 from "../content/docs/psychiatry/neurotic-stress-somatoform-f4/somatoform-disorders.mdx?collection=docs"
import * as __fd_glob_62 from "../content/docs/psychiatry/neurotic-stress-somatoform-f4/obsessive-compulsive-disorder.mdx?collection=docs"
import * as __fd_glob_61 from "../content/docs/psychiatry/neurotic-stress-somatoform-f4/anxiety-disorders.mdx?collection=docs"
import * as __fd_glob_60 from "../content/docs/psychiatry/child-psychiatry-f8-9/other-psychiatric-conditions-in-child-psychiatry.mdx?collection=docs"
import * as __fd_glob_59 from "../content/docs/psychiatry/child-psychiatry-f8-9/oppositional-defiant-and-conduct-disorders.mdx?collection=docs"
import * as __fd_glob_58 from "../content/docs/psychiatry/child-psychiatry-f8-9/autistic-spectrum-disorder-asd.mdx?collection=docs"
import * as __fd_glob_57 from "../content/docs/psychiatry/child-psychiatry-f8-9/attention-deficit-hyperactivity-disorder-adhd.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/psychiatry/child-psychiatry-f8-9/assessment-in-child-psychiatry.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/psychiatry/mood-disorders-f3/major-depressive-disorder.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/psychiatry/mood-disorders-f3/depressive-disorders.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/psychiatry/mood-disorders-f3/bipolar-disorder.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/psychiatry/mood-disorders-f3/approach-to-mood-disturbances.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/psychiatry/behavioural-disorders-f5/sleep-disorders.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/psychiatry/behavioural-disorders-f5/psychosexual-disorders.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/psychiatry/behavioural-disorders-f5/eating-disorders.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/general-surgery/lower-gi/volvulus.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/general-surgery/lower-gi/rectal-prolapse.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/general-surgery/lower-gi/intestinal-obstruction.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/general-surgery/lower-gi/intestinal-ischemia.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/general-surgery/lower-gi/inflammatory-bowel-disease-ulcerative-colitis.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/general-surgery/lower-gi/inflammatory-bowel-disease-crohn-s-disease.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/general-surgery/lower-gi/hemorrhoids.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/general-surgery/lower-gi/diverticular-disease.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/general-surgery/lower-gi/anorectal-fistula.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/general-surgery/lower-gi/anorectal-abscess.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/general-surgery/lower-gi/anal-fissure.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/general-surgery/lower-gi/acute-appendicitis.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/general-surgery/hbp/recurrent-pyogenic-cholangitis.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/general-surgery/hbp/primary-sclerosing-cholangitis.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/general-surgery/hbp/primary-biliary-cirrhosis.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/general-surgery/hbp/pancreatic-cancer.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/general-surgery/hbp/mirizzi-syndrome.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/general-surgery/hbp/malignant-biliary-obstruction-mbo.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/general-surgery/hbp/liver-cirrhosis.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/general-surgery/hbp/liver-abscess.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/general-surgery/hbp/jaundice.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/general-surgery/hbp/hepatocellular-carcinoma-hcc.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/general-surgery/hbp/gallstones.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/general-surgery/hbp/gallbladder-cancer.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/general-surgery/hbp/cholangiocarcinoma.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/general-surgery/hbp/biliary-cysts.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/general-surgery/hbp/acute-pancreatitis.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/general-surgery/hbp/acute-cholecystitis.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/general-surgery/hbp/acute-cholangitis.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/general-surgery/breast/nipple-discharge-or-inversion.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/general-surgery/breast/breast-cancer.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/general-surgery/breast/benign-breast-disease.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/general-surgery/peritonitis.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/general-surgery/index.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/general-surgery/hernia.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/index.mdx?collection=docs"
import { default as __fd_glob_12 } from "../content/docs/psychiatry/substance-abuse-f1/meta.json?collection=docs"
import { default as __fd_glob_11 } from "../content/docs/psychiatry/personality-disorders-f6/meta.json?collection=docs"
import { default as __fd_glob_10 } from "../content/docs/psychiatry/psychotic-disorders-f2/meta.json?collection=docs"
import { default as __fd_glob_9 } from "../content/docs/psychiatry/neurotic-stress-somatoform-f4/meta.json?collection=docs"
import { default as __fd_glob_8 } from "../content/docs/psychiatry/organic-mental-disorders-f0/meta.json?collection=docs"
import { default as __fd_glob_7 } from "../content/docs/psychiatry/child-psychiatry-f8-9/meta.json?collection=docs"
import { default as __fd_glob_6 } from "../content/docs/psychiatry/mood-disorders-f3/meta.json?collection=docs"
import { default as __fd_glob_5 } from "../content/docs/psychiatry/behavioural-disorders-f5/meta.json?collection=docs"
import { default as __fd_glob_4 } from "../content/docs/general-surgery/lower-gi/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../content/docs/general-surgery/hbp/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/general-surgery/breast/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/psychiatry/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/general-surgery/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"general-surgery/meta.json": __fd_glob_0, "psychiatry/meta.json": __fd_glob_1, "general-surgery/breast/meta.json": __fd_glob_2, "general-surgery/hbp/meta.json": __fd_glob_3, "general-surgery/lower-gi/meta.json": __fd_glob_4, "psychiatry/behavioural-disorders-f5/meta.json": __fd_glob_5, "psychiatry/mood-disorders-f3/meta.json": __fd_glob_6, "psychiatry/child-psychiatry-f8-9/meta.json": __fd_glob_7, "psychiatry/organic-mental-disorders-f0/meta.json": __fd_glob_8, "psychiatry/neurotic-stress-somatoform-f4/meta.json": __fd_glob_9, "psychiatry/psychotic-disorders-f2/meta.json": __fd_glob_10, "psychiatry/personality-disorders-f6/meta.json": __fd_glob_11, "psychiatry/substance-abuse-f1/meta.json": __fd_glob_12, }, {"index.mdx": __fd_glob_13, "general-surgery/hernia.mdx": __fd_glob_14, "general-surgery/index.mdx": __fd_glob_15, "general-surgery/peritonitis.mdx": __fd_glob_16, "general-surgery/breast/benign-breast-disease.mdx": __fd_glob_17, "general-surgery/breast/breast-cancer.mdx": __fd_glob_18, "general-surgery/breast/nipple-discharge-or-inversion.mdx": __fd_glob_19, "general-surgery/hbp/acute-cholangitis.mdx": __fd_glob_20, "general-surgery/hbp/acute-cholecystitis.mdx": __fd_glob_21, "general-surgery/hbp/acute-pancreatitis.mdx": __fd_glob_22, "general-surgery/hbp/biliary-cysts.mdx": __fd_glob_23, "general-surgery/hbp/cholangiocarcinoma.mdx": __fd_glob_24, "general-surgery/hbp/gallbladder-cancer.mdx": __fd_glob_25, "general-surgery/hbp/gallstones.mdx": __fd_glob_26, "general-surgery/hbp/hepatocellular-carcinoma-hcc.mdx": __fd_glob_27, "general-surgery/hbp/jaundice.mdx": __fd_glob_28, "general-surgery/hbp/liver-abscess.mdx": __fd_glob_29, "general-surgery/hbp/liver-cirrhosis.mdx": __fd_glob_30, "general-surgery/hbp/malignant-biliary-obstruction-mbo.mdx": __fd_glob_31, "general-surgery/hbp/mirizzi-syndrome.mdx": __fd_glob_32, "general-surgery/hbp/pancreatic-cancer.mdx": __fd_glob_33, "general-surgery/hbp/primary-biliary-cirrhosis.mdx": __fd_glob_34, "general-surgery/hbp/primary-sclerosing-cholangitis.mdx": __fd_glob_35, "general-surgery/hbp/recurrent-pyogenic-cholangitis.mdx": __fd_glob_36, "general-surgery/lower-gi/acute-appendicitis.mdx": __fd_glob_37, "general-surgery/lower-gi/anal-fissure.mdx": __fd_glob_38, "general-surgery/lower-gi/anorectal-abscess.mdx": __fd_glob_39, "general-surgery/lower-gi/anorectal-fistula.mdx": __fd_glob_40, "general-surgery/lower-gi/diverticular-disease.mdx": __fd_glob_41, "general-surgery/lower-gi/hemorrhoids.mdx": __fd_glob_42, "general-surgery/lower-gi/inflammatory-bowel-disease-crohn-s-disease.mdx": __fd_glob_43, "general-surgery/lower-gi/inflammatory-bowel-disease-ulcerative-colitis.mdx": __fd_glob_44, "general-surgery/lower-gi/intestinal-ischemia.mdx": __fd_glob_45, "general-surgery/lower-gi/intestinal-obstruction.mdx": __fd_glob_46, "general-surgery/lower-gi/rectal-prolapse.mdx": __fd_glob_47, "general-surgery/lower-gi/volvulus.mdx": __fd_glob_48, "psychiatry/behavioural-disorders-f5/eating-disorders.mdx": __fd_glob_49, "psychiatry/behavioural-disorders-f5/psychosexual-disorders.mdx": __fd_glob_50, "psychiatry/behavioural-disorders-f5/sleep-disorders.mdx": __fd_glob_51, "psychiatry/mood-disorders-f3/approach-to-mood-disturbances.mdx": __fd_glob_52, "psychiatry/mood-disorders-f3/bipolar-disorder.mdx": __fd_glob_53, "psychiatry/mood-disorders-f3/depressive-disorders.mdx": __fd_glob_54, "psychiatry/mood-disorders-f3/major-depressive-disorder.mdx": __fd_glob_55, "psychiatry/child-psychiatry-f8-9/assessment-in-child-psychiatry.mdx": __fd_glob_56, "psychiatry/child-psychiatry-f8-9/attention-deficit-hyperactivity-disorder-adhd.mdx": __fd_glob_57, "psychiatry/child-psychiatry-f8-9/autistic-spectrum-disorder-asd.mdx": __fd_glob_58, "psychiatry/child-psychiatry-f8-9/oppositional-defiant-and-conduct-disorders.mdx": __fd_glob_59, "psychiatry/child-psychiatry-f8-9/other-psychiatric-conditions-in-child-psychiatry.mdx": __fd_glob_60, "psychiatry/neurotic-stress-somatoform-f4/anxiety-disorders.mdx": __fd_glob_61, "psychiatry/neurotic-stress-somatoform-f4/obsessive-compulsive-disorder.mdx": __fd_glob_62, "psychiatry/neurotic-stress-somatoform-f4/somatoform-disorders.mdx": __fd_glob_63, "psychiatry/neurotic-stress-somatoform-f4/stress-related-disorders.mdx": __fd_glob_64, "psychiatry/organic-mental-disorders-f0/delirium.mdx": __fd_glob_65, "psychiatry/organic-mental-disorders-f0/dementia.mdx": __fd_glob_66, "psychiatry/personality-disorders-f6/cluster-a-odd-personality-disorders.mdx": __fd_glob_67, "psychiatry/personality-disorders-f6/cluster-b-dramatic-personality-disorders.mdx": __fd_glob_68, "psychiatry/personality-disorders-f6/cluster-c-anxious-personality-disorders.mdx": __fd_glob_69, "psychiatry/personality-disorders-f6/personality-and-personality-disorders.mdx": __fd_glob_70, "psychiatry/psychotic-disorders-f2/approach-to-psychotic-symptoms.mdx": __fd_glob_71, "psychiatry/psychotic-disorders-f2/schizophrenia-and-related-disorders.mdx": __fd_glob_72, "psychiatry/substance-abuse-f1/misuse-of-alcohol-and-alcohol-related-disorders.mdx": __fd_glob_73, "psychiatry/substance-abuse-f1/misuse-of-substance.mdx": __fd_glob_74, });